package com.example.taskapp.exception;

public interface IException {

	int ERROR_MISSING_REQUREID_FIELDS = 101;
	int ERROR_RECORD_NOT_FOUND_EXCEPTION = 102;
	int ERROR_INVALID_INPUT = 103;
	int ERROR_SENDING_EMAIL_SENDGRID = 104;
	int ERROR_UNKNOWN_ERROR_ON_SOCIAL_NETWORK = 105;
	int ERROR_FACEBOOK_USER_NOT_VERIFIED = 106;
	int ERROR_INVALID_VALUE_FORMAT=107;
	int ERROR_DUPLICATE_ENTRY=108;
	int ERROR_ENDPOINT_NOT_FOUND=109;
}
